export default {
  NOTIF_TYPE: {
    DANGER: 'danger',
    WARNING: 'warning',
    SUCCESS: 'success',
    INFO: 'info',
  },
  KEY_ACTION: {
    ENTER: 13,
    BACKSPACE: 8,
    COMMA: 188,
    TAB: 9,
    SPACE: 32,
  },
  EXPIRE_TOKEN_MESSAGES: [
    'Token cannot nil',
    'Token invalid',
    'Expire Token',
    'Email not verified',
  ],
  IMG: {
    LOGO: '/ico/67.png',
    LOGO_2x: '/img/logo_2x.png',
    LOGO_WHITE: '/img/logo_white.png',
    LOGO_WHITE_2x: '/img/logo_white_2x.png',
    CSV_ICON: '/img/icon/csv-icon.png',
    ARROW_LEFT: '/img/icon/arrow_left.png',
    ADD_IMAGE_PLACEHOLDER: '/img/icon/add-image-placeholder.png',
    IMAGE_PLACEHOLDER: '/img/icon/add-image-placeholder.png',
    GOOGLE_LOGO: '/img/icon/google-logo.png',
    LINE_ICON: '/img/icon/line_icon.png',
    LINE_ICON_COLORED: '/img/icon/line-icon.png',
    WHATSAPP_ICON: '/img/icon/whatsapp-icon.png',
    WC_ICON: '/img/icon/wc-icon.png',
    FB_ICON: '/img/icon/facebook-logo.png',
    WOO_ICON: '/img/icon/woocommerce-icon.png',
    TELEGRAM_ICON: '/img/icon/telegram-icon.png',
    EN: '/img/icon/en.png',
    ID: '/img/icon/id.png',
    LOGO_NO_IMAGE: '/img/not_available.jpg',
    LOGO_FULL_IMAGE: '/img/logo_full.png',
    WELCOME_IMAGE: '/img/welcome_bubble.png',
    BOB_IMAGE: '/img/bobb_login.png',
    CHAT_BTN_WHITE: '/img/white.png',
    LOGO_SMALL: '/img/logo_talkabot_kecil.png',
    TELEGRAM_GRAY: '/img/icon/telegram_gray.png',
  },
  FILES: {
    IMPORT_TEMPLATE: '/download/importTemplate',
  },
  HTTP_STATUS: {
    OK: 200,
    UNAUTH: 401,
    BAD_REQUEST: 400,
  },
  PERMISSION: {
    REGISTER: false,
  },
  LOCATION: {
    PROVINCE: 'province',
    CITY: 'city',
  },
  STATUS_USER: {
    ADMIN: 'admin',
    AGENT: 'agent',
    CXD: 'cxd',
  },
  BANK_DEFAULT: [
    { label: 'BCA', value: 'bca' },
    { label: 'BNI', value: 'bni' },
    { label: 'BRI', value: 'bri' },
    { label: 'CIMB NIAGA', value: 'cimb-niaga' },
    { label: 'DANAMON', value: 'danamon' },
    { label: 'MANDIRI', value: 'mandiri' },
    { label: 'OCBC', value: 'ocbc' },
    { label: 'PERMATA', value: 'permata' },
  ],
  ICONMENU: {
    analytics: 'fa fa-bar-chart',
    customFlow: 'fa fa-sitemap',
    chatRoom: 'fa fa-comments',
    userEngagement: 'pg-layouts3',
    feedback: 'fa fa-thumbs-up',
    customers: 'fa fa-users',
    broadcast: 'fa fa-bullhorn',
    loyalty: 'fa fa-tag',
    inventory: 'fa fa-cubes',
    products: 'fa fa-th-large',
    order: 'fa fa-shopping-cart',
  }
};
