export default {
  public: {
    login: '/login',
    register: '/register',
  },
  private: {
    profile: '/profile',
    channelManagement: '/channel-management',
    shoppingPage: '/shopping-page',
    analytics: '/analytics',
    productManagement: '/product-management',
    order: '/order',
    userEngagement: '/user-engagement',
    form: '/user-engagement/form',
    history: '/user-engagement/history',
    users: '/user-engagement/users',
    feedback: '/user-engagement/feedback',
    broadcast: '/user-engagement/broadcast',
    socials: '/socials',
    customFlow: '/custom-flow',
    chatRoom: '/chat-room',
    skillset: '/skillset',
    forms: '/forms',
    userBiodata: '/skillset/user-biodata',
    loyalty: '/loyalty',
    customers: '/customers',
    product: '/product',
    product_new: '/product/new',
    product_edit: '/product/edit',
    products: '/products',
    registerChannel: '/registerChannel',
  },
};
